### ISSUE TITLE
[BUG] Long tweets contain a link in tweet cards

### ISSUE THREAD

**Issue by rsssxd** [TheHCJ/Quacker#14]
The same problem exists in Fritter. However, Nitter is not affected by this issue. I wanted to open an issue for this error

**Comment by TheHCJ** [comment]
Should be fixed in v2.1.0

**Comment by rsssxd** [comment]
However, long tweets continue to be missing in the content section. I guess it won't be much of a problem.

However, quoted tweets and tweets showing link content are not displayed correctly in the stream.

**Comment by AndiDink00x** [comment]
This issue still exists in Fritter but for some reason is reported that has been fixed, https://github.com/jonjomckay/fritter/issues/644#issue-1599813900 , https://github.com/jonjomckay/fritter/commit/6df541c9fc6cf3fd3a7ae8a66894ec4515362c23 maybe you could check the changes and maybe find a way to fix this @TheHCJ @j-fbriere

**Comment by j-fbriere** [comment]
I cannot reproduce the issue on the last ci build of Quacker. It has been fixed.
I checked with the Fritter [issue #644](https://github.com/jonjomckay/fritter/issues/644#issue-1599813900) referenced in your comment.

Could you install the [apk file](https://github.com/TheHCJ/Quacker/suites/13446626392/artifacts/737372726) of the last ci build of Quacker and try again?

**Comment by AndiDink00x** [comment]
Long tweets are not shown also to regular(non-blue) tweeter users

Example3:
Long tweet on **Quacker feed**: https://imgur.com/a/T7Yecyw
Long tweet expanded: https://imgur.com/a/OSi8yzc
Long tweet on **Quacker account wall**: https://imgur.com/a/7udnAEg
Long tweet on **Fritter account wall**: https://imgur.com/a/BPFydmD

**Comment by j-fbriere** [comment]
@TheHCJ This is the fix for the long tweets (notes) in feeds.

[fix_14.patch](https://github.com/TheHCJ/Quacker/files/11683959/fix_14.patch)

@AndiDink00x Note that the long tweets are displayed only in feeds, NOT in the tweets of a subscription.

This is normal behavior if you compare with Twitter itself by browsing for instance [https://twitter.com/Navsteva](https://twitter.com/Navsteva).
You'll see that the long tweet starting with _A group of NATO countries_ is in its short form.

**Comment by AndiDink00x** [comment]
@j-fbriere You're right and im also interesting for long tweets to be displayed only on feed, anyway thank you

**Comment by j-fbriere** [comment]
Should be fixed with the last [ci build](https://github.com/TheHCJ/Quacker/suites/13523622022/artifacts/743495992).

**Comment by AndiDink00x** [comment]
@j-fbriere @TheHCJ you guys rock!! i confirm that this issue is fixed maybe this should be closed as "fixed in next release"
