### ISSUE TITLE
[BUG] Link preview images not showing in feed.

### ISSUE THREAD

**Issue by thespirallabyrinth** [TheHCJ/Quacker#45]
**Describe the bug**
Link preview images not showing in feed. Timeline in profile page shows link preview images.

**To Reproduce**
None

**Screenshots**
![IMG_20230531_064924](https://github.com/TheHCJ/Quacker/assets/135082556/6cf859c4-02c1-404d-9eb2-28b28d915e85)

**Device**
Google Pixel 6 Pro, English (UK),Quacker Version 2.2.0

**Comment by TheHCJ** [comment]
Weird, never knew this happened. Thanks for taking time out of your day to make this bug report!

**Comment by TheHCJ** [comment]
Should be fixed in the next release

**Comment by autogris** [comment]
I've tried the last ci build and the problem persists, maybe something changed breaking the current fix to be implemented?
